version: "3.4"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ postgres ]
    ports:
      - 8080:8080
      - 4040:4040
    environment:
      ASPNETCORE_URLS: "https://+:8080;http://+:4040"
      ASPNETCORE_HTTPS_PORT: 8080
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - db.env
