version: "3.4"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [ mssql ]
    ports:
      - "8080:8080"
      - "4040:4040"
    environment:
      ASPNETCORE_URLS: "https://+:8080;http://+:4040"
      ASPNETCORE_HTTPS_PORT: 8080
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: <Type Here Your Password>
      ACCEPT_EULA: Y
    restart: unless-stopped
    ports:
      - 1433:1433
